import Link from "next/link";
import "./globals.css";
import { logout } from "@/lib/action";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/login">Login</Link>
            </li>
            <li>
              <Link href="/register">Register</Link>
            </li>
            <li>
              <Link href="/dashboard">Dashboard</Link>
            </li>
            <form action={logout}>
              <button>로그아웃</button>
            </form>
          </ul>
          {children}
        </div>
      </body>
    </html>
  );
}
